### ISSUE TITLE
License of flymake-lua.el

### ISSUE THREAD

**Issue by szktty** [sroccaserra/emacs#3]
Would you specify a license of flymake-lua.el?

**Comment by sroccaserra** [comment]
Hi, would GNU license suit you? If yes I guess it's done (see commit above).

If not, I can change it. Please describe what you need & why and I'll update the license.

Cheers!

**Comment by szktty** [comment]
Thanks for your support. I hope Apache License 2.0. Because I want to include the customized script of yours in our commercial products.

**Comment by sroccaserra** [comment]
Ok, done (mostly for fun & to learn Apache 2 licence though, as this is super simple code)

Enjoy, cheers!

**Comment by szktty** [comment]
Thanks a lot!
