### ISSUE TITLE
Please create separate repositories

### ISSUE THREAD

**Issue by tarsius** [sroccaserra/emacs#4]
Could you please create separate repositories for packages that have nothing to do with one another? That would help users who install packages as git submodules and would also allow me to add the packages to the Emacsmirror. I am currently working (once more) to mirror all the packages that are available from Melpa. `flymake-lua` is available from Melpa but not yet the Emacsmirror - so if you are inclined to split up this repository, but do not have the time to do it all now, then maybe you should start with that.

**Comment by tarsius** [comment]
Here's a friendly ping for you ;)

**Comment by tarsius** [comment]
Another ping

**Comment by sroccaserra** [comment]
Hi Jonas,

Thank you for your work for Emacsmirror, I have vert little time at the moment, but since this should be fairly quick to handle, I might be able to do it shortly for flymake-lua.

Cheers!

**Comment by sroccaserra** [comment]
Hi Jonas,
Thank you for your work for the Emacsmirror. I have very little time at the moment, sorry for the delay.
I don't think the other files in my emacs directory will interest anyone, so I only moved flymake-lua to its own repo :- https://github.com/sroccaserra/flymake-lua
I hope this will help you!
Cheers!Sébastien.



 

    Le Mercredi 18 janvier 2017 15h45, Jonas Bernoulli <notifications@github.com> a écrit :
 

 Another ping—

**Comment by tarsius** [comment]
Thanks a lot!

I have also updated the Melpa recipe.

**Comment by sroccaserra** [comment]
Nice, thanks.

And just for information, I added a few files (`README.md`, `LICENSE` and `NOTICE `) because I was requested an Apache 2.0 license for this a few years ago, so I keep it this way for this repo.

Cheers!
